In [122]:
import pandas as pd

dataset=pd.read_csv(
    '../datasets/Bangalore.csv'
)

In [123]:
dataset

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator
0,30000000,3340,JP Nagar Phase 1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,Doddanekundi,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,Kengeri,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6202,5364000,590,Chandapura,1,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6203,8716000,1179,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6204,7373000,1143,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6205,4985000,1680,Kasavanahalli,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6206,10900000,1162,Kasavanahalli,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [124]:
dataset.head()

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator
0,30000000,3340,JP Nagar Phase 1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,Doddanekundi,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,Kengeri,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0

In [125]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6207 entries, 0 to 6206
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Price                6207 non-null   int64
 1   Area                 6207 non-null   int64
 2   Location             6207 non-null   object
 3   No. of Bedrooms      6207 non-null   int64
 4   Resale               6207 non-null   int64
 5   MaintenanceStaff     6207 non-null   int64
 6   Gymnasium            6207 non-null   int64
 7   SwimmingPool         6207 non-null   int64
 8   LandscapedGardens    6207 non-null   int64
 9   JoggingTrack         6207 non-null   int64
 10  RainWaterHarvesting  6207 non-null   int64
 11  IndoorGames          6207 non-null   int64
 12  ShoppingMall         6207 non-null   int64
 13  Intercom             6207 non-null   int64
 14  SportsFacility       6207 non-null   int64
 15  ATM                  6207 non-null   int64
 16  ClubHouse            6207 non-null   int64
 17  School               6207 non-null   int64
 18  24X7Security         6207 non-null   int64
 19  PowerBackup          6207 non-null   int64
 20  CarParking           6207 non-null   int64
 21  StaffQuarter         6207 non-null   int64
 22  Cafeteria            6207 non-null   int64
 23  MultipurposeRoom     6207 non-null   int64
 24  Hospital             6207 non-null   int64
 25  WashingMachine       6207 non-null   int64
 26  Gasconnection        6207 non-null   int64
 27  AC                   6207 non-null   int64
 28  Wifi                 6207 non-null   int64
 29  Children'splayarea   6207 non-null   int64
 30  LiftAvailable        6207 non-null   int64
 31  BED                  6207 non-null   int64
 32  VaastuCompliant      6207 non-null   int64
 33  Microwave            6207 non-null   int64
 34  GolfCourse           6207 non-null   int64
 35  TV                   6207 non-null   int64
 36  DiningTable          6207 non-null   int64
 37  Sofa                 6207 non-null   int64
 38  Wardrobe             6207 non-null   int64
 39  Refrigerator         6207 non-null   int64
dtypes: int64(39), object(1)
memory usage: 1.9+ MB

In [126]:
dataset.columns

Index(['Price', 'Area', 'Location', 'No. of Bedrooms', 'Resale',
       'MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', 'Children'splayarea', 'LiftAvailable',
       'BED', 'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV',
       'DiningTable', 'Sofa', 'Wardrobe', 'Refrigerator'],
      dtype='object')

In [127]:
locations=[]
for i in dataset.Location:
    if i not in locations:
        locations.append(i)

In [128]:
locations

['JP Nagar Phase 1',
 'Dasarahalli on Tumkur Road',
 'Kannur on Thanisandra Main Road',
 'Doddanekundi',
 'Kengeri',
 'Horamavu',
 'Thanisandra',
 'Ramamurthy Nagar',
 'Whitefield Hope Farm Junction',
 'Electronic City Phase 1',
 'Yelahanka',
 'Anjanapura',
 'Jalahalli',
 'Kasavanahalli',
 'Bommasandra',
 'Bellandur',
 'RR Nagar',
 'Begur',
 'Hosa Road',
 'Sahakar Nagar',
 'Kadugodi',
 'Jakkur',
 'Jigani',
 'Krishnarajapura',
 'Brookefield',
 'Banashankari',
 'Nelamangala',
 'Attibele',
 'Banaswadi',
 'Kodigehalli',
 'ITPL',
 'Uttarahalli Hobli',
 'Chikkagubbi on Hennur Main Road',
 'Varthur',
 'Vidyaranyapura',
 'Electronic City Phase 2',
 'J. P. Nagar',
 'K. Chudahalli',
 'Narayanaghatta',
 'Anekal City',
 'Sarjapur',
 'Koramangala',
 'Hebbal',
 'Budigere Cross',
 'Bommanahalli',
 'Electronics City',
 'Chikkalasandra',
 'Kogilu',
 'Nayandahalli',
 'Bilekahalli',
 'Muneshwara Nagar',
 'Junnasandra',
 'Narayanapura on Hennur Main Road',
 'Kothanur',
 'Kadugodi Industrial Area',
 'Sarjapur Road Wipro To Railway Crossing',
 'RMV Extension Stage 2',
 'Kudlu',
 'Talaghattapura',
 'Kumbalgodu',
 'Carmelaram',
 'Uttarahalli',
 'Anagalapura Near Hennur Main Road',
 'Avalahalli Off Sarjapur Road',
 'R T  Nagar',
 'JP Nagar Phase 7',
 'Subramanyapura',
 'JP Nagar Phase 4',
 'JP Nagar Phase 8',
 'Amruthahalli',
 'Nagarbhavi',
 'Chandapura',
 'Marsur',
 'JP Nagar Phase 3',
 'JP Nagar Phase 9',
 'Gottigere',
 'Kanakapura Road Beyond Nice Ring Road',
 'Harlur',
 'Konanakunte',
 'Richmond Town',
 'Jayanagar',
 'Domlur',
 'Devanahalli',
 'Hulimavu',
 'Kumaraswamy Layout',
 'Bikasipura',
 'Singasandra',
 'JP Nagar Phase 6',
 'Sanjaynagar',
 'CV Raman Nagar',
 'Padmanabhanagar',
 'Hennur',
 'KPC Layout',
 'R.K. Hegde Nagar',
 'Kannamangala',
 'Yerthiganahalli',
 'Badamanavarthekaval',
 'Kanakapura',
 'Bannerughatta',
 'BTM Layout',
 'Kuvempu Layout on Hennur Main Road',
 'Marathahalli',
 'Rajajinagar',
 'Whitefield',
 'RMV',
 'Bileshivale',
 'Nagawara',
 'HSR Layout',
 'Anjanapura Township',
 'Hurulichikanahalli',
 'Devarachikkana Halli',
 'Sampangiram Nagar',
 'Armane Nagar',
 'Basavanagudi',
 'Yeshwantpur',
 'Battarahalli',
 'K C Krishna Reddy Layout',
 'Adugodi',
 'Kammanahalli',
 'Kalyan Nagar',
 'Kudlu Gate',
 'Kodipalya',
 'Kaggadasapura',
 'Malleswaram',
 'Akshayanagar',
 'Kammmanhalli',
 'Lingarajapuram',
 'Indira Nagar',
 'Nagasandra',
 'Kaval Byrasandra',
 'Sanjay Nagar',
 'Sanjeevini Nagar',
 'Cooke Town',
 'Frazer Town',
 'Vasanth Nagar',
 'NRI Layout',
 'Dasarahalli',
 'Kalkere',
 'Kartik Nagar',
 'Sarjapur Road Till Wipro',
 'hebbal kempapura',
 'Cox Town',
 'Bendre Nagar',
 'Hosakerehalli',
 'Byrathi',
 'Narayanapura',
 'Chamrajpet',
 'Kodihalli on Old Airport Road',
 'Nandini Layout',
 'Ullal Uppanagar',
 'Doddaballapur',
 'Murugesh Palya',
 'Annapurneshwari Nagar',
 'Lingadheeranahalli',
 'Chandra Layout Extension',
 'BTM Layout 2nd Stage',
 '8th Phase JP Nagar',
 'Dodda Banaswadi',
 'Sidedahalli',
 'Hallehalli',
 'HBR Layout',
 'Rajarajeshwari nagar',
 'Uttarahalli Main Road',
 'Poornapragna Housing Society Layout',
 '5th Stage Raja Rajeshwari Nagar',
 'RR Nagar Main Road',
 'DrVishnuvardhan Road',
 'Bharath Housing Society Layout',
 'Hennur Main Road',
 'JP Nagar Phase 5',
 '5th Phase',
 'Kadugondanahalli',
 'Hosa Road Junction',
 'AGS Layout Arehalli',
 'Hosur Main Road',
 'Uttarahalli Road',
 'Poornaprajna Layout',
 'Poorna Pragna Layout',
 'Banashankari 5th stage',
 'Channasandra Layout',
 'JP Nagar 8th Phase',
 'Volagerekallahalli',
 'Mysore Road',
 'Thanisandra Main Road',
 'Koppa Begur Road',
 'Sarjapur Road',
 'Ulsoor',
 'Kathriguppe',
 'Babusabpalya',
 'AECS Layout A Block Singasandra',
 'KR Puram Bhattarahalli',
 'Raja Rajeshwari Nagar 5th Stage',
 'RMV 2nd Stage',
 'Kambipura',
 'Pattanagere Main Road',
 'Ashwathkatte Road',
 'BEML Layout 5th Stage',
 'Shivaji Nagar',
 'Bagalur',
 'Sarjapur Attibele',
 'Domlur Layout',
 'sarjapura attibele road',
 'TC Palya Road',
 'ISRO Layout',
 'Munnekollal',
 'Infantry Road',
 'Richards Town',
 'Pattanagere',
 'Benson Town',
 'Sri Krishna Garden Layout',
 'Kenchena Halli Road',
 'Rajarajeswari Nagar',
 'Bannerghatta Main Road',
 'Mahadevapura',
 'Babusa Palya',
 'Kumaraswamy Layout Vittal Nagar',
 'Ideal Homes Co Operative Housing Society',
 '5th Stage BEML Layout',
 'Dwaraka Nagar',
 'Krishna Garden Road',
 'Gubbalala Main Road',
 'RT Nager',
 'Kadathanamale',
 'Manyata Tech Park Nagawara',
 'Chandapura Anekal Road',
 'BEML Layout',
 'Nagavara',
 'Abbigere',
 'HBR Layout 4th Block',
 'Panathur Road',
 'Poornapragna Housing Society L',
 'Wheeler Road Extension',
 'Hegde Nagar',
 'Vasanthapura Main Road',
 'Hennur Road',
 'Telecom Layout Thanisandra',
 'Manayata Tech Park',
 'MS Ramaiah North City Manayata Tech Park',
 'Near Peenya Industrial Area',
 'Bennigana Halli',
 'Jaibharath Nagar Bangalore',
 'Sadashiva Nagar',
 'Ashok Nagar',
 'Kogilu Road Near Yelahanka',
 'Sompura Gate',
 'Bagaluru',
 'Lavelle Road',
 'Horamavu Banjara Lyout',
 'Kundalahalli',
 'Basaveswarnagar',
 'White Field',
 'Yelahanka New Town',
 'Bannerghatta Road Jigani',
 'Hennagara',
 'EPIP Zone',
 'T C Palya Main Road',
 'CV Raman Nagar Kaggadasapura',
 'Ramanjaneyanagar',
 'Chikkanayakanahalli at Off Sarjapur',
 'Ashoka Road',
 'Sindhi Colony',
 'KR Puram Old Madras Road',
 'Bannerghatta',
 'Begur Road',
 'K P Main Road',
 'Residential Flat Uttarahalli Hobli',
 'Bagaluru Near Yelahanka',
 'Ananth Nagar',
 'Electronic City Phase I',
 '6th phase jp nagar',
 'Ramagondanahalli',
 'Jalahalli West',
 'Off Bannerghatta Road',
 'JP Nagar',
 'Mallasandra',
 'JP Nagar Phase 2',
 'Maruthi Sevanagar',
 'Hoskote',
 'Bangalore Road',
 'Residential FlatUttarahalli Hobli',
 '7th Phase JP Nagar',
 'Padmanabha Nagar',
 'Whitefield Road',
 'Nirman Layout',
 'OMBR Layout',
 'Sompura',
 'Medaralli',
 'Bengaluru Kanakapura Road',
 'Basapura Main Road',
 'Gunjur Balagere Road',
 'Hosa Road Electronic City',
 'Budigere',
 'Hennagara Main Road',
 'Off Cunningham Road',
 'Vijaya Bank Layout',
 'Geddalahalli',
 'Banashankari Stage III',
 'Bellari Road',
 'Bhoopasandra',
 'Kachanayakanahalli',
 'Seegehalli Road',
 'HAL']

In [129]:
print(len(locations))

302

In [130]:
n=[]
for i in range(1,303):
    n.append(i)

In [131]:
print(n)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302]

In [132]:
dataset['Location'].replace(locations,
                        n, inplace=True)

In [133]:
dataset.head()

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator
0,30000000,3340,1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,2,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,3,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,4,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,5,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0

In [134]:
dataset

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator
0,30000000,3340,1,4,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
1,7888000,1045,2,2,0,0,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,4866000,1179,3,2,0,0,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
3,8358000,1675,4,3,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,6845000,1670,5,3,0,1,1,1,1,1,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6202,5364000,590,72,1,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6203,8716000,1179,14,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6204,7373000,1143,14,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6205,4985000,1680,14,3,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
6206,10900000,1162,14,2,0,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [135]:
import numpy as np
def wrangle(df):
    df.replace(9, np.nan, inplace=True)
    df.dropna(inplace=True)
    df.drop(columns = ['Wifi', 'Wardrobe'], inplace=True)
    maskprice = df["Price"]< 100000000
    df = df[maskprice]
    return df

dataset=wrangle(dataset)

In [136]:
X=dataset.iloc[:,1:]

In [137]:
X=X.values

In [138]:
Y=dataset.iloc[:,0]

In [139]:
Y=Y.values

In [140]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [141]:
X_train.shape

(1315, 37)

In [142]:
X_test.shape

(564, 37)

In [143]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [144]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(X_train,Y_train)

RandomForestRegressor()

In [145]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(X_train,Y_train)

DecisionTreeRegressor()

In [146]:
from sklearn.metrics import r2_score
Y_pred=regressor.predict(X_test)
print(r2_score(Y_pred,Y_test))

0.8397819140720577

In [147]:
Y_pred1=rf.predict(X_test)
print(r2_score(Y_pred1,Y_test))

0.8928923278606765

In [148]:
Y_pred2=dt.predict(X_test)
print(r2_score(Y_pred2,Y_test))

0.7829918750945417

In [149]:
import pickle

model=open('../static/models/modelblr.pkl','wb')
pickle.dump(rf,model)
model.close()